# Generated by Django 3.1.4 on 2020-12-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1)),
                ('result', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.CharField(max_length=200)),
                ('question_choice_1', models.CharField(max_length=200)),
                ('question_choice_2', models.CharField(max_length=200)),
                ('question_choice_3', models.CharField(max_length=200)),
                ('question_choice_4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=1)),
                ('question_category', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3)),
                ('test_name', models.CharField(max_length=60)),
                ('questions', models.ManyToManyField(through='tests.Question_Attempt', to='tests.Question_Data')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('average_total', models.CharField(max_length=3)),
                ('average_t1', models.CharField(max_length=3)),
                ('average_t2', models.CharField(max_length=3)),
                ('average_t3', models.CharField(max_length=3)),
                ('tests', models.ManyToManyField(through='tests.Question_Attempt', to='tests.Test_Data')),
            ],
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question_data'),
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test_data'),
        ),
        migrations.AddField(
            model_name='question_attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.student_data'),
        ),
    ]
