# Generated by Django 3.1.4 on 2020-12-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_data_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_data',
            name='student_id',
        ),
        migrations.AddField(
            model_name='test_data',
            name='student_username',
            field=models.CharField(default='bsmith', max_length=20),
            preserve_default=False,
        ),
    ]
