# Generated by Django 3.1.4 on 2020-12-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_student_data_average_t4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
