# Generated by Django 3.1.4 on 2020-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Post',
        ),
    ]
