# Generated by Django 3.1.4 on 2020-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20201221_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='ben stiller', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
