# Generated by Django 3.1.4 on 2020-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20201221_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_data',
            name='category_id',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
