# Generated by Django 3.1.4 on 2020-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_question_data_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_data',
            name='question_copy',
            field=models.CharField(max_length=500),
        ),
    ]
