# Generated by Django 3.1.4 on 2020-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20201221_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_data',
            name='avg1',
            field=models.CharField(default='n/a', max_length=3),
        ),
        migrations.AddField(
            model_name='test_data',
            name='avg2',
            field=models.CharField(default='n/a', max_length=3),
        ),
        migrations.AddField(
            model_name='test_data',
            name='avg3',
            field=models.CharField(default='n/a', max_length=3),
        ),
        migrations.AddField(
            model_name='test_data',
            name='avg4',
            field=models.CharField(default='n/a', max_length=3),
        ),
        migrations.AlterField(
            model_name='question_attempt',
            name='result',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='test_data',
            name='score',
            field=models.CharField(default='n/a', max_length=3),
        ),
    ]
