# Generated by Django 3.1.4 on 2020-12-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_test_data_goal_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_count',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
