# Generated by Django 3.1.4 on 2020-12-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_category_cat_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
