# Generated by Django 3.1.4 on 2020-12-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
