# Generated by Django 3.1.4 on 2020-12-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20201222_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_section',
            name='teacher_username',
            field=models.CharField(default='ssnape', max_length=30),
            preserve_default=False,
        ),
    ]
