# Generated by Django 3.1.4 on 2020-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_class_section_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_data',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Cat_Assignment',
        ),
    ]
